# Generated by Django 5.0.2 on 2024-11-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='uuid',
        ),
    ]
