# Generated by Django 5.0.2 on 2024-12-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_id_device_uuid'),
        ('firmware', '0002_alter_firmware_code_alter_firmware_link_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='firmware.firmware', verbose_name='Firmware do dispositivo'),
        ),
    ]
