# Generated by Django 5.0.2 on 2024-12-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceversion',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
