# Generated by Django 5.0.2 on 2024-12-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_deviceapikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceAPIKey',
        ),
    ]
