# Generated by Django 5.0.2 on 2024-12-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_delete_deviceapikey'),
        ('users', '0004_alter_userapikey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_key_devices', to='users.userapikey', verbose_name='Chave de API associada ao device'),
        ),
    ]
