# Generated by Django 5.0.2 on 2025-01-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_api_key'),
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='wifi.wifi', verbose_name='Wifi associado'),
        ),
    ]
