# Generated by Django 5.0.2 on 2025-03-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_devicestatusbuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatusbuild',
            name='status',
            field=models.CharField(choices=[('in_build', 'In Build'), ('completed_build', 'Completed Build'), ('in_processing', 'In Processing'), ('waiting_to_be_received', 'Waiting to be Received'), ('received', 'Received')], default='in_processing', max_length=22, verbose_name='Status'),
        ),
    ]
