version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ${DOCKER_VOLUME_DOCKER}/Dockerfile
    container_name: api-${DOCKER_PROJECT_NAME}
    command: /start-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DOCKER_NGINX_PORT}:80
    volumes:
        - ${DOCKER_VOLUME_APP}:/code
        - ${DOCKER_VOLUME_STATIC}:/code/run/static
        - ${DOCKER_VOLUME_MEDIA}:/code/run/media
        - ${DOCKER_VOLUME_DOCKER}:/docker
        - ./logs:/code/logs