# Generated by Django 5.0.2 on 2025-01-03 20:43

from django.db import migrations
from apps.role.models import Roles

def create_roles(apps, schema_editor):
    Roles.objects.create(
        code=Roles.ADMIN_CODE,
        name=Roles.ADMIN_NAME
    )
    Roles.objects.create(
        code=Roles.AGENT_CODE,
        name=Roles.AGENT_NAME
    )
    Roles.objects.create(
        code=Roles.TEACHER_CODE,
        name=Roles.TEACHER_NAME
    )


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_roles),
    ]
