# Generated by Django 5.0.2 on 2024-11-25 01:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_id_device_uuid'),
        ('firmware', '0002_alter_firmware_code_alter_firmware_link_bin'),
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='firmware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='firmware.firmware', verbose_name='Firmware associado'),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='GroupDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletion Date/Time')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_device', to='device.device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_device', to='group.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'group_firmware',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', through='group.GroupDevice', to='device.device', verbose_name='Dispositivos do Grupo'),
        ),
    ]
