# Generated by Django 5.0.2 on 2024-11-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_firmware_alter_group_active_groupdevice_and_more'),
        ('wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Wifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='wifi.wifi', verbose_name='Wifi associado'),
        ),
    ]
