# Generated by Django 5.0.2 on 2024-12-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_wifi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Wifi',
            new_name='wifi',
        ),
    ]
