# Generated by Django 5.0.2 on 2024-12-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_user_delete_groupapikey'),
        ('users', '0004_alter_userapikey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='users.userapikey', verbose_name='Chave de API associada ao grupo'),
        ),
    ]
