# Generated by Django 5.0.2 on 2025-02-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_api_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupdevice',
            table='group_device',
        ),
    ]
