# Generated by Django 5.0.2 on 2024-12-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='api_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
