# Generated by Django 5.0.2 on 2024-12-26 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
    ]
