# Generated by Django 5.0.2 on 2025-01-03 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0004_alter_userapikey_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserRoles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('base_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.roles')),
            ],
            options={
                'verbose_name': 'Função do usuario',
                'verbose_name_plural': 'Função dos usuarios',
                'db_table': 'users_base_user_roles',
            },
        ),
        migrations.AddField(
            model_name='baseuser',
            name='roles',
            field=models.ManyToManyField(related_name='users_role', related_query_name='role_user', through='users.BaseUserRoles', to='role.roles'),
        ),
    ]
