# Generated by Django 5.0.2 on 2025-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuserroles_baseuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
