from apps.group.api.group_create_api import GroupCreateApi
from apps.group.api.group_delete_api import  GroupDeleteApi
from apps.group.api.group_list_api import  GroupListApi
from apps.group.api.group_list_by_id_api import GroupByIDApi
from apps.group.api.group_update_api import GroupUpdateApi
from apps.group.api.group_add_firmware_api import GroupAddFirmwareApi
from apps.group.api.group_add_device_api import GroupAddDeviceApi
from apps.group.api.group_add_wifi_api import GroupAddWifiApi
from apps.group.api.group_initialize_ota_api import GroupInitializeOtaApi