from apps.group.services.group_create import group_create
from apps.group.services.group_delete import group_delete
from apps.group.services.group_update import group_update
from apps.group.services.group_add_firmware import group_add_firmware
from apps.group.services.group_add_device import group_add_device
from apps.group.services.group_add_wifi import group_add_wifi
from apps.group.services.group_initialize_ota import group_initialize_ota
from apps.group.services.group_link_api_key import group_link_api_key
from apps.group.services.group_remove_device import group_remove_device