from apps.device.services.device_create import device_create
from apps.device.services.device_delete import device_delete
from apps.device.services.device_update import device_update
from apps.device.services.device_update_version_current import device_update_version_current