# Generated by Django 5.0.2 on 2024-11-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='link_bin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
