# Generated by Django 5.0.2 on 2024-12-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '__first__'),
        ('firmware', '0002_alter_firmware_code_alter_firmware_link_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmware', to='files.file'),
        ),
    ]
