# Generated by Django 5.0.2 on 2025-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware', '0003_firmware_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmware',
            name='link_bin',
        ),
        migrations.AddField(
            model_name='firmware',
            name='use_code',
            field=models.BooleanField(default=True),
        ),
    ]
